language: go
go:
  - 1.1.2
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - git submodule update --init --recursive

install:
  - export GOPATH=$HOME/gopath/src/github.com/cloudfoundry/hm-workspace
  - mkdir -p $GOPATH/bin
  - go install -v github.com/onsi/ginkgo/ginkgo
  - go get -v github.com/apcera/gnatsd
  - pushd ./src/github.com/coreos/etcd
  - ./build
  - mv ./etcd $GOPATH/bin
  - popd
  - mkdir -p $HOME/bin
  - pushd $HOME/bin
  - curl -C - http://apache.osuosl.org/zookeeper/zookeeper-3.4.5/zookeeper-3.4.5.tar.gz | tar -zx
  - mv $HOME/bin/zookeeper-3.4.5 $HOME/bin/zookeeper
  - chmod a+x $HOME/bin/zookeeper/bin/zkServer.sh
  - popd

script:
  - export GOPATH=$HOME/gopath/src/github.com/cloudfoundry/hm-workspace
  - export PATH=$HOME/bin/zookeeper/bin:$GOPATH/bin:$PATH 
  - cd $GOPATH/src/github.com/cloudfoundry/hm9000
  - ginkgo -r -i --randomizeAllSpecs --failOnPending --skip="ZooKeeper"
